### ISSUE TITLE
Popup stopped working after upgrading HomeKit Panel Card to 0.6.3

### ISSUE THREAD

**Issue by rodrigogbs** [DBuit/switch-popup-card#20]
After upgrading HomeKit Panel Card to 0.6.3 version, this popup card stopped working.

System details:

Home Assistant 2022.9.1
Supervisor 2022.08.6
Operating System 8.5
Frontend 20220907.0 - latest
iOS APP

**Comment by rodrigogbs** [comment]
After downgrading HomeKit Panel Card to 0.6.2 version, it works again.

**Comment by DBuit** [comment]
Hi @rodrigogbs,

The new version needs browser mod version 2.0 or higher.
Do you have this running? If not you should not update the card anymore until you update browser mod integration.

**Comment by rodrigogbs** [comment]
@DBuit after upgrading browser_mod it come back to work.

Thanks!
