### ISSUE TITLE
Fan buttons doesn't work in HA version 113

### ISSUE THREAD

**Issue by tomerbs** [DBuit/switch-popup-card#9]
Hi,
After Iv'e update HA to version 113 fan buttons in the switch popup stop working,
you can see my config in the file attached.
Thanks.
[popup.txt](https://github.com/DBuit/switch-popup-card/files/5053639/popup.txt)

**Comment by DBuit** [comment]
Hi @tomerbs ,

just released update that should fix it

**Comment by tomerbs** [comment]
You are the man,
The new version fix it.
Thanks for all the help.

בתאריך יום ג׳, 11 באוג׳ 2020, 16:26, מאת DBuit ‏<notifications@github.com>:
